language: java
jdk:
- oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
- pip
- directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script: "./gradlew -iS build -x test"
env:
  global:
  - secure: 1CviflxrrxGYt3r6CfvFvjV8/bsJwJ68phKQ446TBKaLESyIiUGtjHaxoyFJT2DA27igdcPiyWTjy0dqgElUl5P0WA4LQMor+oANBMt0v3ahstS7e8y4QXjT+sYB9VjLlv1gpRFclGMnlqruhGv1lHvWyn0xxXzeonF8zX05S4OkIm2gwlVlJNW0O+hS2s/7mhH/aloEFCX2R5mnUAdo2AtC1QsBxIDf6+4KSMQnWFz53JdwV4257+SZ7fcW7M3pteWE9TWdMJTglA8AvgidKh6JPMRZ8gNpmL17svb0S0E3b2HE30CHF2eCpdSfgaTlCaZGpY/Q5jNOkdFr37Fm7IhrD2aC26dLmuBYiRo6LQ03U1m8f2vAITz2q2J8p+ElGuvYju9MZWyvOc8G0844cAgjjAeNv21Pg8JWLvghOmuIgrE5fpMHIeKecSIQ/UoA1V2n2kZZ3CQ1l1aGHF3FnEekk0P+ZFOZAfdH/c5xomUK7NRkxKlKiS/87geRV5ZaAvAes/+3kf4c9/54f0RicWBOZsnmXRvnOj2rZz7EGd/SSrrlv14irqxYFNLyTu7O9AUHWjSMRJZYdo33pAEqlgTTt/lEJA3ZUXq4APcdEaHNgWp+ItQdvpBDBHotW/heGTNblPOy2REk2dw0bDDlVW+Uxugl8Kd5cuobLYchUX8=
deploy:
- provider: lambda
  skip_cleanup: true
  region: eu-west-1
  function_name: devternity_ticket_generator
  role: devternity_lambda_executor
  handler_name: lv.latcraft.devternity.tickets.TicketGenerator::generate
  memory_size: 1024
  timeout: 300
  runtime: java8
  zip: build/distributions
  on:
    repo: devternity/ticket-generator
notifications:
  slack:
    secure: dLLFxOFL3Lvb6BiTIM4UYxrrGSARmkq0eTxVyg+QTwLCed+s7vAINSihyCcKF0emthEbUsVHPI5HXYevhf93GTV045Xh/Kf46GXRDZXZeKDQkSbgAkfSVwjFdeQc2tSxk9OVNbQcDh78WkxFuZwS6riqi9pzHnKag/UjrnW0iWAhZwROq22ZTyq2H9TlRHnolJCwr8jRVbxaornetc27nJtGZMIB4S0H0khUfP8u3WNZ2J47jet2AVwR6A7EUYJ8MKyUs+PLrNc+adXfW0ZlREuo2XkKzlzQyvqlZTF+/naJ3/JPZRet2T3CgNiSuEBAtvnfgpHP71SCPvphq7CXLC6OgbfRCBgo4J7TgXICalfaQDH3tzqSFaNRalT/X/B04WgFlPh/8UJ6QDkFroATxgkW8aQkQo3L3apvO7+xAiE+tftTwANjEutYkgdz4CwKwBYTnSik+0FNK4qm6czlrnl9ob4eEOxq+kcXhLFZvtO8w5TVhZaO2SIq9S46mfBWnS+9+pfQe/XLL19PqnPrbDbpLuPS/bLy6sCTL3Va1exTLk3gVRBtmFMIkRMP2CaTgYw7aqLVnOotneIS4qIT7lxqs4KNELHGMRXrYgjhMMRiGQeUq+bSCwHncSgYD1+Ey2PT8rM3tWIiF86XWdompyiYKNzJgt8GpJd9cSGdAzA=
