language: java
jdk:
- oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
- pip
- directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script: "./gradlew -iS build -x test"
deploy:
- provider: lambda
  skip_cleanup: true
  region: eu-west-1
  description: DevTernity ticket generator
  function_name: devternity_ticket_generator
  handler_name: TicketGenerator::generate
  module_name: lv.latcraft.devternity.tickets
  role: 
    secure: PRUzlLrtEeqEOKyJWTIGjuWsYgYSdul3hEIQA/gFrhAY8JKCdExbHuceq06hoX9gt4rR1gyyqAEmdABqaZNPgYmsSc3+ImPN6VhQNVOKydBdFBe3W3h4bjMTjlTJVsAPwwpr+Oxccp/m/6dUKn/sw1D7jBdoAVRvtkfkHhRKnMgrOkTAGkBL+icmGJuA+aUnKYn+DC4OUsXLI5tQNaVQEoKFMYHAhus3jULar0Dkwaeqi2BMQhRQpJ9vXLULGfP0XZZXxDve64KHoJDDzqtFD7oXdIck8JbaF1QcBnzix3Kh4VNuI+EL9pq0O0ERr6ne6Gx0m44/g0gIs60oaFEXr82gNPj7wCgV2YsHyTbauHIdT8yDROVFPF4yG5lEE5uYxGIoJbCyUiB5lvGjqRn/q/QdIb8cSvrB/EAZeoNxsBTlOhu2Mrhz0n8DCd6Au+smyHQi6NnvZgbE1wjU02AzE5KzDLX+Lo4jEVz60ehLYhiYyaS07mGqnM1qEhHf84FpTEpDwWXIKHb1mrotpoIqmjy9LpCTmti6PvSqw/o2A+eXW/6JtrVc26NLULuo0woAaJqzj81DnFvjZyYtzZfIV76hkG8ROPMZG76VeVIz/NAVJOYB5dJtXN+uoWo47uzJQs1JBCviY51nf3TgU939IOMfsq8hlkfc8KaEAmtBrHM=
  access_key_id: 
    secure: H0OZYSY0DDv6w4k5feDJBTeaIGeY9PKGZ3oP1JoYUjMBnVoF6DyFT2sgGIPsF1RCd7+0afAa4uPC16PGyEVnsvV8W7vOU2yB/bf50Addi+DlQBImbLyX5UNAvGHokn+1y6cbjrVZEGZ2gSZSW6233pqSwznZPBACFxTmMERk3Jj7khd0cukUjtQarY/nb5CaP8TLETcTZDN7gw6e3WuR74elxxMdW/fLXMIGhCJIQ0rF8ww0Pv172jiNTKFDRQeZSO5Wwydf3sEGYVSIgtU0oPG9JhSz6593jo46k7ueDO8psRvlzQ80Oj34TD6UiHKSrpKvcDePooWvJ5Q4dHs5dWaaXSCRsJ9JJ9P3d+S8k+/9Cg7yAq/tt+13RUpdUHMH0IcSufaqPBhPtKgylGhFd2wEj8WMrp+2anYbsTR+LxxS2QiBTSIPhIFUFr6HGQ7jLEevKJ4bRCXRE4eKPXDAV5c8mbyK+E/55KtdKozTbzOuVo5We95OnyxM5e8NUnIT/iVi0hi/I/x6Zjc5QFST0O21N/QrBNg3ntYQSrddE7X11grZJbJz9RGfIvEHmxcWb08vMVo1IkKo2lIDJZy7+BQyj4m2WY9XAiap+BxycQ135KnN1RG5eXSJE3HACWwB+BMeKSGOcQGoYq+gjRL8TWGsC7VjK6vm+rRLvpUwD20=
  secret_access_key: 
    secure: KDlTQ07PH9y2KLpf1LHPqw5ydrZp1guJs40H7eXXMEkQV21yEr69HubdsOrEXDjY+tvqINO1QdoRLGm+mNG6oC/pghSKnO5k4+A6Ab/9CSfp4vw9w/58dhau/FXBrKAQmNOOIjKq2ql1A5BPkkgWSFgeLmDS4WlVpIZyMZGXfOSSIlSNwtMQyQonIt/5JORxqOwW9HjUP/YwcfiJgg+50H5utLDxZfEuVmuN0lYSd1jrYHiR8MxPENe34Py0NpwAJYgiTB3et30U9OJJBgH3du+4DEc9YkWLHj+TMUY27DGXoYHTmpDwf/V1ToMdHXCcy0fsnaKAQ+XQ6SMk0G1+GoUymO4+2M1O82BnjUhkn/d+diczPcR/r3g9Sq9bXzTPKvFf+e9IXsA5YNM9aVQDnbfyzaqLKTN8p9v5l51KY6JQo2HM9zR1QR3sRQiDxhqEfRMgKGKp42jBf87NEyaPBhxh9ECEcwZJDDsx3xhoAXbemYFQZZezZfdoBFpu11H7cmCZtOTLosQroSEmzAIGZ8uOelRHgI6yBEbBeaIAGkY8oDyGeCZN1FPyT2DAHdqeQfBl2ceEr13QpkUxtg/xSq+4QWKLGOmil8bjLHmiS5XpTw7xRxlYnKifzrP2KKfBYPMQFgCBYWXW6/jFpX3Q8HgDylY0WO/+UwYcUjfxVv8=
  memory_size: 1024
  timeout: 300
  runtime: java8
  zip: build/distributions/ticket-generator.zip
  on:
    repo: devternity/ticket-generator
    branch: master
notifications:
  slack:
    secure: dLLFxOFL3Lvb6BiTIM4UYxrrGSARmkq0eTxVyg+QTwLCed+s7vAINSihyCcKF0emthEbUsVHPI5HXYevhf93GTV045Xh/Kf46GXRDZXZeKDQkSbgAkfSVwjFdeQc2tSxk9OVNbQcDh78WkxFuZwS6riqi9pzHnKag/UjrnW0iWAhZwROq22ZTyq2H9TlRHnolJCwr8jRVbxaornetc27nJtGZMIB4S0H0khUfP8u3WNZ2J47jet2AVwR6A7EUYJ8MKyUs+PLrNc+adXfW0ZlREuo2XkKzlzQyvqlZTF+/naJ3/JPZRet2T3CgNiSuEBAtvnfgpHP71SCPvphq7CXLC6OgbfRCBgo4J7TgXICalfaQDH3tzqSFaNRalT/X/B04WgFlPh/8UJ6QDkFroATxgkW8aQkQo3L3apvO7+xAiE+tftTwANjEutYkgdz4CwKwBYTnSik+0FNK4qm6czlrnl9ob4eEOxq+kcXhLFZvtO8w5TVhZaO2SIq9S46mfBWnS+9+pfQe/XLL19PqnPrbDbpLuPS/bLy6sCTL3Va1exTLk3gVRBtmFMIkRMP2CaTgYw7aqLVnOotneIS4qIT7lxqs4KNELHGMRXrYgjhMMRiGQeUq+bSCwHncSgYD1+Ey2PT8rM3tWIiF86XWdompyiYKNzJgt8GpJd9cSGdAzA=
